spring:
  datasource:
    url: jdbc:tracing:oracle:thin:@localhost:1522/xe
    username: customer
    password: customer
    driver-class-name: io.opentracing.contrib.jdbc.TracingDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      properties:
        spring.json.add.type.headersfalse: false
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
opentracing:
  jaeger:
    udp-sender:
      host: localhost
      port: 6831
    service-name: sales-customer