apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  containers:
  - env:
    - name: KAFKA_ADVERTISED_LISTENERS
      value: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
    - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
      value: "true"
    - name: KAFKA_INTER_BROKER_LISTENER_NAME
      value: INTERNAL
    - name: KAFKA_LISTENERS
      value: INTERNAL://:29092,EXTERNAL://:9092
    - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      value: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
    image: obsidiandynamics/kafka:2.3.0-11
    name: kafka
    ports:
    - containerPort: 2181
    - containerPort: 9092
    resources: {}
  restartPolicy: Never
status: {}
