apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Windows\system32\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-sales-order
  name: mongodb-sales-order
spec:
  ports:
  - name: "27019"
    port: 27019
    targetPort: 27017
  selector:
    io.kompose.service: mongodb-sales-order
status:
  loadBalancer: {}
