apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kafdrop
  name: kafdrop
spec:
  containers:
  - env:
    - name: KAFKA_BROKERCONNECT
      value: kafka:29092
    image: obsidiandynamics/kafdrop:3.27.0
    name: kafdrop
    ports:
    - containerPort: 9000
    resources: {}
  restartPolicy: Never
status: {}
