apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Windows\system32\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: kafdrop
  name: kafdrop
spec:
  ports:
  - name: "9001"
    port: 9001
    targetPort: 9000
  selector:
    io.kompose.service: kafdrop
status:
  loadBalancer: {}
